# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  jobs:
    pre_install:
      - curl -fsSL https://ollama.com/install.sh | sh

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
