# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  jobs:
    pre_install:
      - curl -L https://ollama.com/download/ollama-linux-amd64.tgz -o ollama-linux-amd64.tgz
      - mkdir /tmp/ollama && tar -C /tmp/ollama -xzf ollama-linux-amd64.tgz
      - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/ollama/lib
      - /tmp/ollama/bin/ollama serve &
      - curl --connect-timeout 5 --retry-all-errors --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 60 'http://localhost:11434'

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
